[package]
name = "graphminton"
version = "0.1.0"
edition = "2024"

[dependencies]
helix-rs = "0.1.10"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
tokio = "1.48.0"
chrono = "0.4"
csv = "1.4.0"
